language: csharp
mono: none
dotnet: 2.1.300-preview1-008174
install:
- dotnet restore
script:
- dotnet build
before_install:
- sudo apt-get install nunit-console
after_script:
- nunit-console build/netcoreapp2.0/NosCore.Tests.dll