language: csharp
mono: none
sudo: required
dist: xenial
addons:
    snaps:
      - name: dotnet-sdk
        classic: true
        channel: latest/beta
sudo: required
language: csharp
mono: none
script:
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
    - dotnet test test/NosCore.Tests/NosCore.Tests.csproj --no-build --filter TestCategory!=OPTIONAL-TEST /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./tools/'
    - cd tools
    - ./csmacnz.Coveralls --opencover -i coverage.xml --repoToken $COVERALLS_REPO_TOKEN --commitBranch $TRAVIS_BRANCH
after_script:
    - dotnet test test/NosCore.Tests/NosCore.Tests.csproj --no-build --filter TestCategory=OPTIONAL-TEST
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws ecr get-login --region us-west-2 --no-include-email
    - aws lambda invoke --function-name noscore-travis --region us-west-2 --payload '{"Build_Id":"'"$TRAVIS_JOB_ID"'", "Travis_Branch":"'"$TRAVIS_BRANCH"'", "Travis_Test_Result":"'"$TRAVIS_TEST_RESULT"'", "Travis_Commit":"'"$TRAVIS_COMMIT"'", "Travis_Repo_Slug":"'"$TRAVIS_REPO_SLUG"'", "Travis_Pull_Request":"'"$TRAVIS_PULL_REQUEST"'"}' outputfile
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
