language: csharp
mono: none
dotnet: 2.1.101
stages:
    - compile
    - test
install:
    - dotnet restore
script: 
    - dotnet build
after_script:
    - dotnet test test/NosCore.Tests/NosCore.Tests.csproj
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --region us-west-2 --no-include-email)
    export PARAM_LAMBDA='{"Build_Id":'$TRAVIS_BUILD_ID', "Travis_Branch":"'"$TRAVIS_BRANCH"'", "Travis_Commit":"'"$TRAVIS_COMMIT"'", "Travis_Pull_Request":'"$TRAVIS_PULL_REQUEST"', "Travis_Repo_Slug":'"$TRAVIS_REPO_SLUG"'}}'
    echo "$PARAM_LAMBDA"
    - eval $(aws lambda invoke --invocation-type Event  --log-type Tail  --function-name noscore-travis --region us-west-2 --payload $PARAM_LAMBDA outputfile)
