language: csharp
mono: none
sudo: required
dist: trusty
dotnet: 2.1
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD='password'
    - PGHOST=localhost
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
stages:
    - compile
    - test
services:
    - postgresql
install:
    - dotnet restore
script: 
    - dotnet build
after_script:
    - dotnet test test/NosCore.Tests/NosCore.Tests.csproj
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws ecr get-login --region us-west-2 --no-include-email
    - aws lambda invoke --function-name noscore-travis --region us-west-2 --payload '{"Build_Id":"'"$TRAVIS_JOB_ID"'", "Travis_Branch":"'"$TRAVIS_BRANCH"'", "Travis_Commit":"'"$TRAVIS_COMMIT"'", "Travis_Repo_Slug":"'"$TRAVIS_REPO_SLUG"'", "Travis_Pull_Request":"'"$TRAVIS_PULL_REQUEST"'"}' outputfile
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1