version: '3.7'

services:
  db:
    container_name: noscore-db
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - noscore-network

  master:
    container_name: noscore-master
    environment:
      - PORT=${MASTER_PORT}
      - DB_HOST=${DB_HOST}
    build:
      context: ./
      dockerfile: deploy/Dockerfile-master
    restart: unless-stopped
    ports:
      - ${MASTER_PORT}:${MASTER_PORT}
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/netcoreapp5.0/linux-x64:/app/build/bin
      - ./configuration/:/app/configuration


  world:
    container_name: noscore-world
    environment:
      - WEBAPI_PORT=${WORLD_WEBAPI_PORT}
      - WORLD_PORT=${WORLD_PORT}
      - MASTER_HOST=master
      - DB_HOST=${DB_HOST}
      - HOST=${HOST}
    build:
      context: ./
      dockerfile: deploy/Dockerfile-world
    restart: unless-stopped
    ports:
      - ${WORLD_WEBAPI_PORT}:${WORLD_WEBAPI_PORT}
      - ${WORLD_PORT}:${WORLD_PORT}
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/netcoreapp5.0/linux-x64:/app/build/bin
      - ./configuration/:/app/configuration
      
  login:
    container_name: noscore-login
    environment:
      - LOGIN_PORT=${LOGIN_PORT}
      - MASTER_HOST=master
      - DB_HOST=${DB_HOST}
      - HOST=${HOST}
    build:
      context: ./
      dockerfile: deploy/Dockerfile-login
    restart: unless-stopped
    ports:
      - ${LOGIN_PORT}:${LOGIN_PORT}
    expose:
      - 5432
    networks: 
      - noscore-network
    volumes:
      - ./build/netcoreapp5.0/linux-x64:/app/build/bin
      - ./configuration/:/app/configuration

networks:
  noscore-network:
    driver: bridge